# Generated by Django 5.2.1 on 2025-05-26 02:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('poder', 'Poder'), ('tributos', 'Tributos'), ('saúde', 'Saúde'), ('energia', 'Energia'), ('trabalhista', 'Trabalhista')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/')),
                ('content', models.TextField()),
                ('publish_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado')], default='draft', max_length=10)),
                ('is_pro_only', models.BooleanField(default=False)),
                ('vertical', models.CharField(choices=[('poder', 'Poder'), ('tributos', 'Tributos'), ('saúde', 'Saúde'), ('energia', 'Energia'), ('trabalhista', 'Trabalhista')], default='poder', max_length=50)),
            ],
            options={
                'ordering': ['-publish_at'],
            },
        ),
    ]
